NODE_VERSION=8.0
HOST_PORT=3000
CONTAINER_NAME=recaptcha_demo
SITE_KEY=6LcqbyYUAAAAAGaYHN7BbAyAVmpH4taeZMBrftur
SECRET_KEY=6LcqbyYUAAAAALiTLq3oLq9iUjCn_U7-SPIryP4x

docker run --name $CONTAINER_NAME -v `pwd`:/usr/app -p $HOST_PORT:8080 -e RECAPTCHA_SITE_KEY=$SITE_KEY -e RECAPTCHA_SECRET_KEY=$SECRET_KEY -it node:$NODE_VERSION /bin/bash

